export const SIGN_IN = 'SIGN_IN';
export const SIGN_UP = 'SIGN_UP';
export const SIGN_IN_RESPONSE = 'SIGN_IN_RESPONSE';
export const SIGN_UP_RESPONSE = 'SIGN_UP_RESPONSE';
export const GET_DATA = 'GET_DATA';
export const GET_DATA_RESPONSE = 'GET_DATA_RESPONSE';

export const LOAD_TASKS = 'LOAD_TASKS';
export const TASKS_LOADED = 'TASKS_LOADED';
export const PUSH_TASK = 'PUSH_TASK';
export const TASK_PUSHED = 'TASK_PUSHED';
export const EDIT_TASK = 'EDIT_TASK';
export const TASK_EDITED = 'TASK_EDITED';
export const DELETE_TASK = 'DELETE_TASK';
export const TASK_DELETED = 'TASK_DELETED';
export const SWITCH_STATUS = 'SWITCH_STATUS';
export const STATUS_SWITCHED = 'STATUS_SWITCHED';
export const SET_EDITABLE = 'SET_EDITABLE';
export const TASK_CREATOR_STATUS = 'TASK_CREATOR_STATUS';
export const ADD_COLUMN = 'ADD_COLUMN';
export const COLUMN_ADDED = 'COLUMN_ADDED';
export const REMOVE_COLUMN = 'REMOVE_COLUMN';
export const COLUMN_REMOVED = 'COLUMN_REMOVED';
export const CHANGE_COLUMN_NAME = 'CHANGE_COLUMN_NAME';
export const COLUMN_NAME_CHANGED = 'COLUMN_NAME_CHANGED';
export const HOVER_ELEMENT = 'HOVER_ELEMENT';


